package com.example.patheaseapp.Hazard

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

// Data model representing a single hazard/barrier point, backed by the
// `hazards` table in our dedicated hazard-reporting Supabase project.
@Serializable
data class Hazard(
    val id: String = "", // uuid, generated by Supabase — leave blank when inserting new
    val type: String,
    val lat: Double,
    val lng: Double,
    @SerialName("photo_url") val photoUrl: String? = null,
    @SerialName("reported_by") val reportedBy: String? = null,
    @SerialName("is_active") val isActive: Boolean = true,
    @SerialName("confirmed_removed_count") val confirmedRemovedCount: Int = 0,
    @SerialName("created_at") val createdAt: String? = null, // set by DB default, not by us
    val distanceMeters: Float = 0f // client-side only, not stored in DB — recalculated locally
)